"""initial migration

Revision ID: 975513b01d78
Revises: 
Create Date: 2024-06-17 21:31:03.930986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '975513b01d78'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_author'))
    )
    op.create_index(op.f('ix_blog_author_name'), 'blog_author', ['name'], unique=False)
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_country'))
    )
    op.create_index(op.f('ix_country_name'), 'country', ['name'], unique=True)
    op.create_table('customer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer'))
    )
    op.create_index(op.f('ix_customer_name'), 'customer', ['name'], unique=True)
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_language'))
    )
    op.create_index(op.f('ix_language_name'), 'language', ['name'], unique=True)
    op.create_table('manufacturer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manufacturer'))
    )
    op.create_index(op.f('ix_manufacturer_name'), 'manufacturer', ['name'], unique=True)
    op.create_table('blog_user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_blog_user_customer_id_customer')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_user'))
    )
    op.create_index(op.f('ix_blog_user_customer_id'), 'blog_user', ['customer_id'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_order_customer_id_customer')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order'))
    )
    op.create_index(op.f('ix_order_customer_id'), 'order', ['customer_id'], unique=False)
    op.create_index(op.f('ix_order_timestamp'), 'order', ['timestamp'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('cpu', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturer.id'], name=op.f('fk_product_manufacturer_id_manufacturer')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product'))
    )
    op.create_index(op.f('ix_product_manufacturer_id'), 'product', ['manufacturer_id'], unique=False)
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=True)
    op.create_index(op.f('ix_product_year'), 'product', ['year'], unique=False)
    op.create_table('blog_article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.Column('translation_of_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['blog_author.id'], name=op.f('fk_blog_article_author_id_blog_author')),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], name=op.f('fk_blog_article_language_id_language')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_blog_article_product_id_product')),
    sa.ForeignKeyConstraint(['translation_of_id'], ['blog_article.id'], name=op.f('fk_blog_article_translation_of_id_blog_article')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_article'))
    )
    op.create_index(op.f('ix_blog_article_author_id'), 'blog_article', ['author_id'], unique=False)
    op.create_index(op.f('ix_blog_article_language_id'), 'blog_article', ['language_id'], unique=False)
    op.create_index(op.f('ix_blog_article_product_id'), 'blog_article', ['product_id'], unique=False)
    op.create_index(op.f('ix_blog_article_timestamp'), 'blog_article', ['timestamp'], unique=False)
    op.create_index(op.f('ix_blog_article_title'), 'blog_article', ['title'], unique=False)
    op.create_index(op.f('ix_blog_article_translation_of_id'), 'blog_article', ['translation_of_id'], unique=False)
    op.create_table('blog_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['blog_user.id'], name=op.f('fk_blog_session_user_id_blog_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_session'))
    )
    op.create_index(op.f('ix_blog_session_user_id'), 'blog_session', ['user_id'], unique=False)
    op.create_table('order_item',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('fk_order_item_order_id_order')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_order_item_product_id_product')),
    sa.PrimaryKeyConstraint('product_id', 'order_id', name=op.f('pk_order_item'))
    )
    op.create_table('product_country',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], name=op.f('fk_product_country_country_id_country')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_product_country_product_id_product')),
    sa.PrimaryKeyConstraint('product_id', 'country_id', name=op.f('pk_product_country'))
    )
    op.create_table('product_review',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_product_review_customer_id_customer')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_product_review_product_id_product')),
    sa.PrimaryKeyConstraint('product_id', 'customer_id', name=op.f('pk_product_review'))
    )
    op.create_index(op.f('ix_product_review_timestamp'), 'product_review', ['timestamp'], unique=False)
    op.create_table('blog_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['blog_article.id'], name=op.f('fk_blog_view_article_id_blog_article')),
    sa.ForeignKeyConstraint(['session_id'], ['blog_session.id'], name=op.f('fk_blog_view_session_id_blog_session')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_view'))
    )
    op.create_index(op.f('ix_blog_view_timestamp'), 'blog_view', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_view_timestamp'), table_name='blog_view')
    op.drop_table('blog_view')
    op.drop_index(op.f('ix_product_review_timestamp'), table_name='product_review')
    op.drop_table('product_review')
    op.drop_table('product_country')
    op.drop_table('order_item')
    op.drop_index(op.f('ix_blog_session_user_id'), table_name='blog_session')
    op.drop_table('blog_session')
    op.drop_index(op.f('ix_blog_article_translation_of_id'), table_name='blog_article')
    op.drop_index(op.f('ix_blog_article_title'), table_name='blog_article')
    op.drop_index(op.f('ix_blog_article_timestamp'), table_name='blog_article')
    op.drop_index(op.f('ix_blog_article_product_id'), table_name='blog_article')
    op.drop_index(op.f('ix_blog_article_language_id'), table_name='blog_article')
    op.drop_index(op.f('ix_blog_article_author_id'), table_name='blog_article')
    op.drop_table('blog_article')
    op.drop_index(op.f('ix_product_year'), table_name='product')
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.drop_index(op.f('ix_product_manufacturer_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_order_timestamp'), table_name='order')
    op.drop_index(op.f('ix_order_customer_id'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_blog_user_customer_id'), table_name='blog_user')
    op.drop_table('blog_user')
    op.drop_index(op.f('ix_manufacturer_name'), table_name='manufacturer')
    op.drop_table('manufacturer')
    op.drop_index(op.f('ix_language_name'), table_name='language')
    op.drop_table('language')
    op.drop_index(op.f('ix_customer_name'), table_name='customer')
    op.drop_table('customer')
    op.drop_index(op.f('ix_country_name'), table_name='country')
    op.drop_table('country')
    op.drop_index(op.f('ix_blog_author_name'), table_name='blog_author')
    op.drop_table('blog_author')
    # ### end Alembic commands ###
